site_name: KTH Digital Research Handbook v0.1
site_url: https://kth-library.github.io/kth-digital-research-handbook
repo_url: https://github.com/KTH-Library/kth-digital-research-handbook
repo_name: KTH digital research handbook
copyright: '© 2025 KTH Royal Institute of Technology'

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Figtree
  logo: assets/images/kth-logo.svg
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs

  palette:
    - scheme: slate
      primary: custom
    # dark theme
      toggle:
        icon: material/brightness-7
        name: Dark mode
      accent: pink

    # light theme
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: custom
      accent: pink

# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code#configuration
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

# Footer
extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/KTH-Library/kth-digital-research-handbook
validation:
# https://www.mkdocs.org/user-guide/configuration/#validation
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

plugins:
  - search:
      lang: en
      # https://squidfunk.github.io/mkdocs-material/plugins/search/#config.pipeline
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  # https://ultrabug.github.io/mkdocs-static-i18n/getting-started/quick-start/
  # https://github.com/squidfunk/mkdocs-material/discussions/2346
  - i18n:
      # https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-search/
      reconfigure_search: true
      # Can be 'folder' or 'suffix' e.g index.sv.md
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: sv
          name: Svenska
          build: true
          # Nav Translations
          # https://ultrabug.github.io/mkdocs-static-i18n/setup/localizing-navigation/
          nav:
            - Hem: sv/index.md
            - Hur gör jag för att:
                - Komma åt Jupyter vid EOSC EU-noden: how_to_guides/EOSC_Jupyter.md
                - Bidra till denna handbok: how_to_guides/contribute.md
            - Introduktion:
                - Introduktion: introduction/intro.md
                - Målgrupp: introduction/audience.md
            - Jag vill:
                - Arbeta med data från planering till publicering: methodologies/research-data-lifecycle.md
                - Arbeta med öppenhet och transparens: methodologies/openness.md
                - Arbeta med Konfidentiella data: methodologies/confidential-data.md
                - Använda kvalitativa forskningsmetoder: methodologies/qualitative-research.md
                - Använda kvantitativ forskning: methodologies/quantitative-research.md
                - Arbeta i stora projekt: methodologies/large-projects.md
                - Arbeta med data-drivna metoder: methodologies/data-science.md
                - Använda automatiserade arbetsflöden: methodologies/workflows.md
            - Kunskapsbas:
                - KTH-stöd: knowledge_base/kth-support.md
                - Communities: knowledge_base/communities.md
                - Hitta data: knowledge_base/finding-data.md
                - Hitta lagring och beräkning: knowledge_base/storage.md
                - Nationella resurser: knowledge_base/national.md
                - Översikt digitala verktyg: knowledge_base/tools.md
                - Regelverksöversikt: knowledge_base/regulation.md
                - Krav från finansiärer: knowledge_base/funder-mandates.md
                - Krav från förlag: knowledge_base/publisher-requirements.md
            - Om:
                - Användarvillkor: about/terms.md
                - Cookiepolicy: about/cookie-policy.md

nav:
  # When updating the nav, remember to update the i18n plugin nav as well
  - Home: index.md
  - How to:
      - Access Jupyter notebook at EOSC EU node: how_to_guides/EOSC_Jupyter.md
      - Contribute to this handbook: how_to_guides/contribute.md
  - Introduction:
      - Introduction: introduction/intro.md
      - Target audience: introduction/audience.md
  - I want to:
      - Manage data from plan to publish: methodologies/research-data-lifecycle.md
      - Work with openness and transparency: methodologies/openness.md
      - Work with confidential data: methodologies/confidential-data.md
      - Do Qualitative research: methodologies/qualitative-research.md
      - Do Quantitative research: methodologies/quantitative-research.md
      - Work in large projects: methodologies/large-projects.md
      - Do data-driven science: methodologies/data-science.md
      - Use automated workflows: methodologies/workflows.md
  - Knowledge base:
      - KTH support: knowledge_base/kth-support.md
      - Communities: knowledge_base/communities.md
      - Finding data: knowledge_base/finding-data.md
      - Finding storage and compute: knowledge_base/storage.md
      - National resources: knowledge_base/national.md
      - Digital Tools overview: knowledge_base/tools.md
      - Regulatory overview: knowledge_base/regulation.md
      - Funder mandates: knowledge_base/funder-mandates.md
      - Publisher requirements: knowledge_base/publisher-requirements.md
  - About:
      - Terms of Use: about/terms.md
      - Cookies Policy: about/cookie-policy.md
